### ISSUE TITLE
Doesn't launch unless I edit the .desktop file

### ISSUE THREAD

**Issue by pizzadude** [flathub/io.github.hakuneko.HakuNeko#1]
Upon installation of the flatpak, Hakuneko Desktop doesn't launch from the menu.
I checked the .desktop file, and found this in the exec:

Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/usr/lib/hakuneko-desktop/hakuneko io.github.hakuneko.HakuNeko

If I change it to:

Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 io.github.hakuneko.HakuNeko

then the program launches.

**Comment by maxtron95** [comment]
@barthalion How can I modify the `Exec=` in a flatpak?

**Comment by TingPing** [comment]
@creepertron95 `desktop-file-edit --set-key=Exec --set-value=... /app/share/applications/...desktop`

**Comment by maxtron95** [comment]
It should be fixed now. I modified the `Exec=` to `/usr/lib/hakuneko-desktop/hakuneko` to `hakuneko-desktop %U`

**Comment by pizzadude** [comment]
@creepertron95 no, still not fixed.

/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=hakuneko-desktop --file-forwarding io.github.hakuneko.HakuNeko @@u %U @@
bwrap: execvp hakuneko-desktop: No such file or directory

It works if I remove the " --command=hakuneko-desktop"

**Comment by maxtron95** [comment]
@TingPing I tried a desktop-file-edit. Any tips to remove the `--command=` section of the flatpak .desktop file? @pizzadude says it works if ` --command=hakuneko-desktop` is removed.

**Comment by barthalion** [comment]
It's not flatpak that does something wrong, the desktop file is wrong. The manifest uses `hakuneko` as the command but desktop launcher used (and still uses) a command which does not exist or just doesn't work.

**Comment by pizzadude** [comment]
Yep, you need to change the "--command=hakuneko-desktop" line to "--command=hakuneko"

**Comment by maxtron95** [comment]
@pizzadude I changed the command `hakuneko-desktop` to `hakuneko`

**Comment by pizzadude** [comment]
Confirmed fixed.
